spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

  datasource:
    minimum-idle: 10
    maximum-pool-size: 60
    pool-name: report-db-pool
#    auto-commit: false
#    idle-timeout: 59000
    jdbc-url: jdbc:h2:mem:report;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  cache:
    ehcache:
      config: classpath:ehcache.xml
apis:
  kakao:
    host: https://dapi.kakao.com
    access-key: b905c3938904dd33b8cde6756a967a16

